/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import uangkyu.Activity;

/**
 *
 * @author Alfian Andi Nugraha
 */
public class Modal extends javax.swing.JFrame {

    /**
     * Creates new form Modal
     */
    public Modal(int index, Dashboard dashboard) {
        initComponents();
        
        this.incomeRadioButton.setSelected(true);
        this.incomeRadioButton.setActionCommand("1");
        this.outcomeRadioButton.setActionCommand("0");
        this.buttonGroup1.add(incomeRadioButton);
        this.buttonGroup1.add(outcomeRadioButton);
        
        this.inputName.setText(dashboard.activityList.activities.get(index).getDescription());
        this.inputNominal.setText(String.valueOf(dashboard.activityList.activities.get(index).getNominal()));
        this.dashboard = dashboard;
        this.indexRow = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        inputName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputNominal = new javax.swing.JTextField();
        incomeRadioButton = new javax.swing.JRadioButton();
        outcomeRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        addActivityButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deleteActivityButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(21, 132, 103));

        inputName.setBackground(new java.awt.Color(255, 255, 255));
        inputName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputName.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Aktifitas");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nominal");

        inputNominal.setBackground(new java.awt.Color(255, 255, 255));
        inputNominal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        incomeRadioButton.setBackground(new java.awt.Color(21, 132, 103));
        incomeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        incomeRadioButton.setText("Pemasukan");
        incomeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeRadioButtonActionPerformed(evt);
            }
        });

        outcomeRadioButton.setBackground(new java.awt.Color(21, 132, 103));
        outcomeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        outcomeRadioButton.setSelected(true);
        outcomeRadioButton.setText("Pengeluran");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        addActivityButton.setBackground(new java.awt.Color(21, 132, 103));
        addActivityButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addActivityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addActivityButtonMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update");

        javax.swing.GroupLayout addActivityButtonLayout = new javax.swing.GroupLayout(addActivityButton);
        addActivityButton.setLayout(addActivityButtonLayout);
        addActivityButtonLayout.setHorizontalGroup(
            addActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(addActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addActivityButtonLayout.createSequentialGroup()
                    .addGap(0, 55, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 56, Short.MAX_VALUE)))
        );
        addActivityButtonLayout.setVerticalGroup(
            addActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(addActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addActivityButtonLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        deleteActivityButton.setBackground(new java.awt.Color(240, 84, 84));
        deleteActivityButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteActivityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteActivityButtonMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hapus");

        javax.swing.GroupLayout deleteActivityButtonLayout = new javax.swing.GroupLayout(deleteActivityButton);
        deleteActivityButton.setLayout(deleteActivityButtonLayout);
        deleteActivityButtonLayout.setHorizontalGroup(
            deleteActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(deleteActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deleteActivityButtonLayout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );
        deleteActivityButtonLayout.setVerticalGroup(
            deleteActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(deleteActivityButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deleteActivityButtonLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel4.setForeground(new java.awt.Color(240, 84, 84));
        jLabel4.setText("Close");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addActivityButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(addActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(inputNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(outcomeRadioButton)
                        .addComponent(incomeRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(inputNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(incomeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outcomeRadioButton)
                .addGap(33, 33, 33))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incomeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeRadioButtonActionPerformed

    private void addActivityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addActivityButtonMouseClicked
        String name = this.inputName.getText();
        int nominal = Integer.parseInt(this.inputNominal.getText());
        int type = Integer.parseInt(this.buttonGroup1.getSelection().getActionCommand());

        Activity activity = new Activity();
        activity
            .setNominal(nominal)
            .setDescription(name)
            .setType(type);
        
        Object data[] = {0, name, Activity.convertTypeToText(type), nominal};
        this.dashboard.activityList.activities.set(this.indexRow, activity);
        this.dashboard.updateRow(indexRow, data);
        this.dashboard.refreshNominal();
        this.setVisible(false);
    }//GEN-LAST:event_addActivityButtonMouseClicked

    private void deleteActivityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteActivityButtonMouseClicked
        this.dashboard.activityList.activities.remove(this.indexRow);
        this.dashboard.deleteRow(this.indexRow);
        this.dashboard.refreshNominal();
        this.setVisible(false);
    }//GEN-LAST:event_deleteActivityButtonMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Modal().setVisible(true);
//            }
//        });
//    }

    Dashboard dashboard;
    int indexRow;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addActivityButton;
    private javax.swing.JPanel addActivityButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel deleteActivityButton;
    private javax.swing.JRadioButton incomeRadioButton;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputNominal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton outcomeRadioButton;
    // End of variables declaration//GEN-END:variables
}
