/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.ArrayList;
import Models.Activity;
import Models.User;
import Services.ActivityService;
import Services.UserService;
import Utils.Time;
import java.util.Date;
import javax.swing.JLabel;

/**
 *
 * @author Alfian Andi Nugraha
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Sebelum masuk kedalam Dashboard, maka dicari user terlebih dahulu berdasarkan email.txt
     * mencari usernya menggunakan method dari UserService yaitu getCurrentUser
     * data user yang sudah login dimasukkan kedalam property this.user yang bisa digunakan untuk data tambahan dalam menambahkan activity
     */
    public Dashboard() {
        try {
            this.user = new UserService().getCurrentUser();
            initComponents();
        } catch (Exception err) {
            new Login().setVisible(true);
        }
        Time time = new Time();
        this.endIntervalDate.setDate(time.getDate());
        this.inputDate.setDate(time.getDate());
        time.getDate().setDate(1);
        this.startIntervalDate.setDate(time.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        inputDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputNominal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        buttonToSetIncome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttonToSetExpense = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        totalNominal = new javax.swing.JLabel();
        totalNominalText = new javax.swing.JLabel();
        currencyTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalIncome = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalOutcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        endIntervalDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel10 = new javax.swing.JLabel();
        startIntervalDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UangKyu - Aplikasi Pelacak Keuangan");
        setMinimumSize(new java.awt.Dimension(1096, 658));
        setResizable(false);
        setSize(new java.awt.Dimension(1096, 658));

        jPanel2.setBackground(new java.awt.Color(82, 128, 120));
        jPanel2.setMinimumSize(new java.awt.Dimension(1096, 658));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(347, 658));

        jPanel3.setBackground(new java.awt.Color(82, 128, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(347, 71));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UangKyu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel12)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        inputDescription.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inputDescription.setMargin(new java.awt.Insets(0, 10, 0, 10));
        inputDescription.setPreferredSize(new java.awt.Dimension(265, 45));
        inputDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDescriptionActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(43, 43, 43));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 43, 43));
        jLabel1.setText("Aktifitas");

        inputNominal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inputNominal.setMargin(new java.awt.Insets(0, 10, 0, 10));
        inputNominal.setPreferredSize(new java.awt.Dimension(265, 45));
        inputNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNominalActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(43, 43, 43));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 43, 43));
        jLabel2.setText("Nominal");

        inputDate.setPreferredSize(new java.awt.Dimension(265, 45));

        jLabel3.setBackground(new java.awt.Color(43, 43, 43));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 43, 43));
        jLabel3.setText("Tanggal");

        buttonToSetIncome.setBackground(new java.awt.Color(82, 128, 120));
        buttonToSetIncome.setForeground(new java.awt.Color(255, 255, 255));
        buttonToSetIncome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonToSetIncome.setPreferredSize(new java.awt.Dimension(265, 45));
        buttonToSetIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonToSetIncomeMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pemasukan");

        javax.swing.GroupLayout buttonToSetIncomeLayout = new javax.swing.GroupLayout(buttonToSetIncome);
        buttonToSetIncome.setLayout(buttonToSetIncomeLayout);
        buttonToSetIncomeLayout.setHorizontalGroup(
            buttonToSetIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(buttonToSetIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonToSetIncomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buttonToSetIncomeLayout.setVerticalGroup(
            buttonToSetIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(buttonToSetIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonToSetIncomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        buttonToSetExpense.setBackground(new java.awt.Color(240, 84, 84));
        buttonToSetExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonToSetExpense.setPreferredSize(new java.awt.Dimension(265, 45));
        buttonToSetExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonToSetExpenseMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pengeluaran");

        javax.swing.GroupLayout buttonToSetExpenseLayout = new javax.swing.GroupLayout(buttonToSetExpense);
        buttonToSetExpense.setLayout(buttonToSetExpenseLayout);
        buttonToSetExpenseLayout.setHorizontalGroup(
            buttonToSetExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(buttonToSetExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonToSetExpenseLayout.createSequentialGroup()
                    .addGap(0, 99, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 98, Short.MAX_VALUE)))
        );
        buttonToSetExpenseLayout.setVerticalGroup(
            buttonToSetExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(buttonToSetExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonToSetExpenseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        logoutButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(240, 84, 84));
        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonToSetExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNominal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonToSetIncome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addGap(152, 152, 152))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(buttonToSetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonToSetExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(28, 28, 28))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(749, 107));

        totalNominal.setBackground(new java.awt.Color(82, 128, 120));
        totalNominal.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        totalNominal.setForeground(new java.awt.Color(82, 128, 120));
        totalNominal.setText("2.000.000");

        totalNominalText.setBackground(new java.awt.Color(82, 128, 120));
        totalNominalText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        totalNominalText.setForeground(new java.awt.Color(82, 128, 120));
        totalNominalText.setText("Total");

        currencyTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        currencyTotal.setForeground(new java.awt.Color(82, 128, 120));
        currencyTotal.setText("Rp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(totalNominalText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(currencyTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalNominal)
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currencyTotal)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(totalNominalText)
                            .addGap(43, 43, 43))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(totalNominal)
                            .addGap(23, 23, 23)))))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(313, 107));

        jLabel6.setBackground(new java.awt.Color(82, 128, 120));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(82, 128, 120));
        jLabel6.setText("Rp");

        jLabel7.setBackground(new java.awt.Color(82, 128, 120));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(82, 128, 120));
        jLabel7.setText("Pemasukan");

        totalIncome.setBackground(new java.awt.Color(82, 128, 120));
        totalIncome.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        totalIncome.setForeground(new java.awt.Color(82, 128, 120));
        totalIncome.setText("2.000.000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalIncome))
                    .addComponent(jLabel7))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(totalIncome))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(313, 107));

        jLabel8.setBackground(new java.awt.Color(240, 84, 84));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 84, 84));
        jLabel8.setText("Rp");

        jLabel9.setBackground(new java.awt.Color(240, 84, 84));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 84, 84));
        jLabel9.setText("Pengeluaran");

        totalOutcome.setBackground(new java.awt.Color(240, 84, 84));
        totalOutcome.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        totalOutcome.setForeground(new java.awt.Color(240, 84, 84));
        totalOutcome.setText("2.000.000");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalOutcome))
                    .addComponent(jLabel9))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(totalOutcome))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tanggal", "Deskripsi", "Nominal", "Jenis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(32);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        endIntervalDate.setPreferredSize(new java.awt.Dimension(265, 45));
        endIntervalDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                endIntervalDatePropertyChange(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(43, 43, 43));
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sampai");

        startIntervalDate.setPreferredSize(new java.awt.Dimension(265, 45));
        startIntervalDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startIntervalDatePropertyChange(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(43, 43, 43));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startIntervalDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endIntervalDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(38, 38, 38))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endIntervalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startIntervalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescriptionActionPerformed

    private void inputNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNominalActionPerformed
    
    /**
     * memanggil insertData ketika button "Pemasukan" di klik
     * insertData dengan argumen "+"
     * @param evt 
     */
    private void buttonToSetIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonToSetIncomeMouseClicked
        this.insertData("+");
    }//GEN-LAST:event_buttonToSetIncomeMouseClicked

    /**
     * memanggil insertData ketika button "Pengeluaran" di klik
     * insertData dengan argumen "-"
     * @param evt 
     */
    private void buttonToSetExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonToSetExpenseMouseClicked
        this.insertData("-");
    }//GEN-LAST:event_buttonToSetExpenseMouseClicked

    /**
     * menampilkan modal edit form ketika salah satu baris dari tabel di klik
     * @param evt 
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = this.jTable1.getSelectedRow();
        int id = Integer.parseInt(this.jTable1.getValueAt(index, 0).toString());
        String updatedAt = this.jTable1.getValueAt(index, 1).toString();
        String description = this.jTable1.getValueAt(index, 2).toString();
        float nominal = Float.parseFloat(this.jTable1.getValueAt(index, 3).toString());
        
        Modal modal = new Modal(this);
        modal
            .setDescription(description)
            .setId(id)
            .setUpdatedAt(updatedAt)
            .setNominal(nominal)
            .run();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * memperbarui tampilan ketika input tanggal "From"/ "Dari" diubah
     * @param evt 
     */
    private void startIntervalDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startIntervalDatePropertyChange
        try {
            this.refreshUI();
        } catch (Exception err) {
            
        }
    }//GEN-LAST:event_startIntervalDatePropertyChange

    /**
     * memperbarui tampilan ketika input tanggal "To" / "Sampai" diubah
     * @param evt 
     */
    private void endIntervalDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_endIntervalDatePropertyChange
        try {
            this.refreshUI();
        } catch (Exception err) {
            
        }
    }//GEN-LAST:event_endIntervalDatePropertyChange

    /**
     * melakukan logout pada user, ketika user mengklik logout
     * @param evt 
     */
    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        try {
            new UserService().logout();
            new Login().setVisible(true);
            this.setVisible(false);
        } catch (Exception err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_logoutButtonMouseClicked
    
    /**
     * insertData digunakan untuk menambahkan activity berdasarkan parameter typeActivity
     * jika typeActivity adalah '+' maka masuk kedalam income / pemasukan
     * tapi, jika typeActivity adalah '-' maka masuk kedalam expense / pengeluaran
     * @param typeActivity 
     */
    public void insertData(String typeActivity) {
        try {
            Float.parseFloat(this.inputNominal.getText());
        } catch (Exception err) {
            this.alert.showMessageDialog(null, "Silahkan input nominal dengan benar");
        }
        
        try {
            this.inputDate.getDate().getTime();
        } catch (Exception err) {
            this.alert.showMessageDialog(null, "Silahkan input tanggal dengan benar");
        }
        
        Time time = new Time();
        time.setDate(this.inputDate.getDate());
        
        String description = this.inputDescription.getText();
        float nominal = Math.abs(Float.parseFloat(this.inputNominal.getText()));
        String dateAt = time.parseDatetime();
        
        ActivityService activityService = new ActivityService();
        
        activityService
            .setDescription(description)
            .setNominal(nominal)
            .setDateAt(dateAt)
            .setUser(this.user);
        
        try {
            if (typeActivity.equals("+")) {
                activityService.insertIncome();
            } else {
                activityService.insertExpense();
            }
            this.refreshUI();
            this.resetForm();
        } catch (Exception err) {
            this.alert.showMessageDialog(null, err.getMessage());
        }
    }
    
    /**
     * centeringTableColumn() digunakan untuk mengubah posisi setiap baris tabel ke tengah
     */
    public void centeringTableColumn() {
        DefaultTableCellRenderer centerAlign = new DefaultTableCellRenderer();
        centerAlign.setHorizontalAlignment(JLabel.CENTER);
        for(int i = 0; i < 5; i++) {
            this.jTable1.getColumnModel().getColumn(i).setCellRenderer(centerAlign);
        }
        
        ((DefaultTableCellRenderer)this.jTable1.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);
    }
    
    /**
     * refreshUI() digunakan untuk memperbarui tampilan aplikasi
     * yang diperbarui yaitu total nominal dan isi dari tabel pada aplikasi
     */
    public void refreshUI() {
        ((DefaultTableModel)this.jTable1.getModel()).setRowCount(0);
        
        this.centeringTableColumn();
        
        ActivityService activityService = new ActivityService();
        activityService.setUser(user);
        
        String startInterval = (new Time()).setDate(this.startIntervalDate.getDate()).parseDatetime();
        String endInterval = (new Time()).setDate(this.endIntervalDate.getDate()).parseDatetime();
        
        try {
            ArrayList<Activity> activities = activityService.getByInterval(startInterval, endInterval);
            for(Activity item : activities) {
                DefaultTableModel tableModel = (DefaultTableModel)this.jTable1.getModel();
                String dateAt = item.getDateAt().replace(" 00:00:00", "");
                tableModel.addRow(
                    new Object[]{item.getId(), dateAt, item.getDescription(), item.getNominal(), item.getType().getName()}
                );
            }
        } catch(Exception err) {
            System.out.println(err.getMessage());
        }
        float totalIncome = 0;
        float totalOutcome = 0;
        float totalNominal = 0;
        
        try {
            totalIncome = activityService.getTotalIncome(startInterval, endInterval);
            totalOutcome = activityService.getTotalExpense(startInterval, endInterval);
            totalNominal = totalIncome - totalOutcome;
        } catch (Exception err) {
            System.out.println(err.getMessage());
        }
        
        this.totalIncome.setText(String.valueOf(totalIncome));
        this.totalOutcome.setText(String.valueOf(totalOutcome));
        this.totalNominal.setText(String.valueOf(totalNominal));
        
        if(totalNominal < 0) {
            this.totalNominalText.setForeground(new Color(240,84,84));
            this.totalNominal.setForeground(new Color(240,84,84));
            this.currencyTotal.setForeground(new Color(240,84,84));
        } else {
            this.totalNominalText.setForeground(new Color(82,128,120));
            this.totalNominal.setForeground(new Color(82,128,120));
            this.currencyTotal.setForeground(new Color(82,128,120));
        }
    }
    
    /**
     * resetForm() digunakan untuk melakukan reset pada form input activity
     * tanggalnya akan diubah ke waktu sekarang
     */
    public void resetForm() {
        this.inputDescription.setText("");
        this.inputNominal.setText("");
        
        Time time = new Time();
        this.inputDate.setDate(time.getDate());
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//    }
    private JOptionPane alert;
    public User user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonToSetExpense;
    private javax.swing.JPanel buttonToSetIncome;
    private javax.swing.JLabel currencyTotal;
    private org.jdesktop.swingx.JXDatePicker endIntervalDate;
    private org.jdesktop.swingx.JXDatePicker inputDate;
    private javax.swing.JTextField inputDescription;
    private javax.swing.JTextField inputNominal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoutButton;
    private org.jdesktop.swingx.JXDatePicker startIntervalDate;
    private javax.swing.JLabel totalIncome;
    private javax.swing.JLabel totalNominal;
    private javax.swing.JLabel totalNominalText;
    private javax.swing.JLabel totalOutcome;
    // End of variables declaration//GEN-END:variables
}
